package com.litongjava.yt.utils;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.nio.file.Files;
import java.nio.file.Paths;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.litongjava.tio.utils.commandline.ProcessResult;
import com.litongjava.tio.utils.commandline.ProcessUtils;
import com.litongjava.tio.utils.environment.EnvUtils;
import com.litongjava.tio.utils.snowflake.SnowflakeIdUtils;
import com.litongjava.yt.builder.YtDlpOption;
import com.litongjava.yt.builder.YtDlpOptionBuilder;
import com.litongjava.yt.consts.YtDlpConst;

public class YtDlp {
  public static final Logger log = LoggerFactory.getLogger(YtDlp.class);

  // Download URLs for different operating systems
  public static final String windows_download_url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe";
  public static final String linux_download_url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux";
  public static final String mac_os_download_url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos";

  /**
   * Downloads the yt-dlp executable if it does not already exist.
   * @throws IOException 
   * @throws ProtocolException 
   * @throws MalformedURLException 
   */
  public static String downloadYtDlp() throws MalformedURLException, ProtocolException, IOException {
    String ytDlpName = getYtDlpName();
    File file = new File(ytDlpName);
    if (file.exists()) {
      // If the file already exists, no need to download it
      return ytDlpName;
    }

    String downloadUrl = getYtDlpUrl();
    HttpURLConnection connection = null;

    try {
      connection = URLUtils.getConnection(downloadUrl);
      connection.setRequestMethod("GET");

      // Start the connection
      int responseCode = connection.getResponseCode();
      if (responseCode == HttpURLConnection.HTTP_OK) {
        try (InputStream inputStream = connection.getInputStream();
            OutputStream outputStream = Files.newOutputStream(file.toPath())) {
          byte[] buffer = new byte[4096];
          int bytesRead;
          while ((bytesRead = inputStream.read(buffer)) != -1) {
            outputStream.write(buffer, 0, bytesRead);
          }
          System.out.println("Download completed: " + file.getAbsolutePath());
        }

        // add permissions
        if (!file.setExecutable(true)) {
          log.error("Failed to set executable permission for " + file.getAbsolutePath());
        }
      } else {
        log.error("Download failed, server returned response code: " + responseCode);
      }

    } finally {
      if (connection != null) {
        connection.disconnect();
      }
    }
    return file.getAbsolutePath();
  }

  /**
   * Returns the file where yt-dlp is or should be downloaded.
   *
   * @return File object representing the yt-dlp executable.
   */
  public static String getYtDlpName() {
    String os = System.getProperty("os.name").toLowerCase();
    if (os.startsWith("windows")) {
      String str = EnvUtils.getStr(YtDlpConst.YT_DLP_BIN_WIN);
      if (str != null && Files.exists(Paths.get(str))) {
        return str;
      }
      return "yt-dlp.exe";
    } else if (os.startsWith("linux")) {

      String str = EnvUtils.getStr(YtDlpConst.YT_DLP_BIN_LINUX);
      if (str != null && Files.exists(Paths.get(str))) {
        return str;
      }
      return "yt-dlp_linux";
    }
    String str = EnvUtils.getStr(YtDlpConst.YT_DLP_BIN_MAC);
    if (str != null && Files.exists(Paths.get(str))) {
      return str;
    }
    return "yt-dlp_macos";
  }

  /**
   * Returns the download URL for the current operating system.
   *
   * @return A string representing the download URL.
   */
  public static String getYtDlpUrl() {
    String os = System.getProperty("os.name").toLowerCase();
    if (os.startsWith("windows")) {
      return windows_download_url;
    } else if (os.startsWith("linux")) {
      return linux_download_url;
    }
    return mac_os_download_url;
  }

  /**
   * Downloads the audio for the specified URL. Options must be built using the
   * audio() method of YtDlpOptionBuilder.
   *
   * @param options The options for downloading and converting audio.
   * @return The output generated by yt-dlp.
   * @throws InterruptedException
   * @throws IOException
   */
  public static ProcessResult execute(String logDir, YtDlpOption option) throws IOException, InterruptedException {
    String command = option.toCommand();
    return execute(logDir, command);
  }

  public static ProcessResult execute(YtDlpOptionBuilder builder) throws IOException, InterruptedException {
    YtDlpOption option = builder.build();
    return execute(option);
  }

  /**
   * Internal execute method that downloads yt-dlp (if needed) and runs the
   * command.
   *
   * @param option The command-line options.
   * @return The output from the command execution.
   * @throws InterruptedException
   * @throws IOException
   */
  public static ProcessResult execute(String logDir, String options) throws IOException, InterruptedException {
    String ytDlpPath = YtDlp.downloadYtDlp();

    long id = SnowflakeIdUtils.id();
    String commandString = ytDlpPath + "  " + options;
    log.info("Task id: " + id + " Executing command: " + commandString);
    String[] commandArray = commandString.split("  ");

    ProcessBuilder processBuilder = new ProcessBuilder(commandArray);
    ProcessResult result = ProcessUtils.execute(new File(logDir), processBuilder);
    result.setTaskId(id);
    return result;
  }

  public static ProcessResult execute(YtDlpOption options) throws IOException, InterruptedException {
    String command = options.toCommand();
    return execute(command);
  }

  public static ProcessResult execute(String options) throws IOException, InterruptedException {
    String ytDlpPath = YtDlp.downloadYtDlp();

    long id = SnowflakeIdUtils.id();
    String commandString = ytDlpPath + "  " + options;
    log.info("Task id: " + id + " Executing command: " + commandString);
    String[] commandArray = commandString.split("  ");

    ProcessBuilder processBuilder = new ProcessBuilder(commandArray);
    File logDir = new File("yt-dlp-task-log" + File.separator + id);
    if (!logDir.exists()) {
      logDir.mkdirs();
    }
    ProcessResult result = ProcessUtils.execute(logDir, processBuilder);
    result.setTaskId(id);
    return result;
  }

}
